# via https://www.mediawiki.org/wiki/Docker/Docker_Hub#Initial_docker-compose.yml
services:
  web:
    image: mediawiki
    ports:
      - 80:80
    volumes:
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - database:/var/www/data
      - images:/var/www/html/images
volumes:
    database:
    images:
